/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package flooferland.showbiz.showformat;

import java.io.InputStream;
import java.util.zip.GZIPInputStream;

// TODO: Make an API for reading/parsing the show intermediate files from an InputStream

public class ShowFormat {
    public static void fromInputStream(InputStream stream) {
        try (var gzipInputStream = new GZIPInputStream(stream)) {
            int firstByte = gzipInputStream.read();
            if (firstByte != -1) {
                System.out.printf("First byte: 0x%02X%n", firstByte);
            } else {
                System.out.println("The file is empty.");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
