/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package flooferland.showbiz.showformat;

import org.junit.jupiter.api.Test;

import java.io.FileInputStream;
import java.io.FileNotFoundException;

class LibraryTest {
    private static final String Path = "C:/Users/FlooferLand/Desktop/looney.bin";
    
    @Test void someLibraryMethodReturnsTrue() throws FileNotFoundException {
        System.out.println();
        
        try {
            ShowFormat.fromIntermediate(new FileInputStream(Path));
        } catch (Exception e) {
            e.printStackTrace();
        }
        // assertTrue(classUnderTest.fromIntermediate(), "fromIntermediate should return 'true'");
        
        System.out.println();
    }
}
