/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package flooferland.showbiz.showformat;

import org.junit.jupiter.api.Test;

import java.io.FileInputStream;
import java.io.FileNotFoundException;

import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    private static final String Path = "C:/Users/FlooferLand/Desktop/Monkees-Medley.bin";
    
    @Test void someLibraryMethodReturnsTrue() throws FileNotFoundException {
        ShowFormat.fromInputStream(new FileInputStream(Path));
        // assertTrue(classUnderTest.fromInputStream(), "fromInputStream should return 'true'");
    }
}
